version: '3.8'

services:
  log-manager:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Mount source code for development
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - "3000:3000"

  # Remove nginx for development
  nginx:
    profiles:
      - disabled
