FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy source code
COPY . .

# Create data directory
RUN mkdir -p /app/data/logs

EXPOSE 3000

ENV DOCKER_HOST unix:///var/run/docker.sock

CMD ["npm", "run", "dev"]
